import { createReadStream } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * File storage for photos and PDFs. Local disk now (UPLOAD_DIR); in AWS an S3 adapter with the
 * same three calls replaces it. Keys are generated by the app, never taken from user input.
 */
const DEFAULT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../uploads');
const root = () => path.resolve(process.env.UPLOAD_DIR || DEFAULT_DIR);

function resolveKey(key) {
  const full = path.resolve(root(), key);
  if (!full.startsWith(root() + path.sep)) throw new Error('Invalid storage key');
  return full;
}

export async function putObject(key, buffer) {
  const full = resolveKey(key);
  await mkdir(path.dirname(full), { recursive: true });
  await writeFile(full, buffer, { flag: 'wx' });
}

export function getObjectStream(key) {
  return createReadStream(resolveKey(key));
}

/** Detects the real file type from its first bytes (the browser-supplied type is not trusted). */
export function sniffType(buffer) {
  const b = buffer;
  if (b.length > 3 && b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff) return { mime: 'image/jpeg', ext: '.jpg' };
  if (b.length > 8 && b.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return { mime: 'image/png', ext: '.png' };
  if (b.length > 12 && b.subarray(0, 4).toString('ascii') === 'RIFF' && b.subarray(8, 12).toString('ascii') === 'WEBP') return { mime: 'image/webp', ext: '.webp' };
  if (b.length > 5 && b.subarray(0, 5).toString('ascii') === '%PDF-') return { mime: 'application/pdf', ext: '.pdf' };
  return null;
}
