"""
Writes src/styles/dark.css: the dark theme for the whole app, generated from Tailwind's palette.

Instead of a `dark:` class on thousands of elements, dark mode (html.dark) remaps the palette:
  - surfaces: white cards/inputs -> dark surface, the canvas -> near black;
  - slate 50-500 (panels, borders, muted text) -> dark greys;
  - light tints of every hue (50-300: badges, tiles, borders) -> the hue mixed into the dark surface;
  - text in dark shades (slate/hue 600-950) -> the matching light shade, so it stays readable;
  - text in light shades (50-300, used on coloured fills) keeps its original colour.
Solid fills (hue 400-950, slate 600-950: buttons, avatars, backdrops) are left as they are.
Run again after changing the palette:  python frontend/scripts/build-dark-theme.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
theme = open(os.path.join(ROOT, '..', 'node_modules', 'tailwindcss', 'theme.css'), encoding='utf-8').read()
app_css = open(os.path.join(ROOT, 'src', 'index.css'), encoding='utf-8').read()

colors = {}
for name, val in re.findall(r'--color-([a-z]+-\d+):\s*([^;]+);', theme):
    colors[name] = val.strip()
for name, val in re.findall(r'--color-([a-z]+-\d+):\s*([^;]+);', app_css):  # the app's own blue scale
    colors[name] = val.strip()

HUES = ['red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose']
SURFACE = '#111a2b'
CANVAS = '#0a111d'
# Dark greys for slate 50-500 (backgrounds, borders, muted text).
SLATE_DARK = {50: '#162133', 100: '#1b273b', 200: '#27354b', 300: '#39485f', 400: '#6a788e', 500: '#8d9ab0'}
# Greys for slate text: 300 (faint placeholders) stays faint but readable, 600-950 become light.
SLATE_TEXT = {300: '#5b6a80', 600: '#a7b3c5', 700: '#c1cad8', 800: '#d9e0ea', 900: '#e8edf4', 950: '#f4f7fb'}
TINT = {50: 14, 100: 22, 200: 34, 300: 52}
TEXT_UP = {600: 400, 700: 300, 800: 200, 900: 100, 950: 50}
BS = '\\'


def esc(cls):
    return cls.replace(':', BS + ':').replace('/', BS + '/').replace('.', BS + '.')


def text_rule(cls, value):
    sels = [
        f':where(html.dark) .{esc(cls)}',
        f':where(html.dark) .{esc("hover:" + cls)}:hover',
        f':where(html.dark) .group:hover .{esc("group-hover:" + cls)}',
        f':where(html.dark) .{esc("focus:" + cls)}:focus',
    ]
    return f"{', '.join(sels)} {{ color: {value}; }}"


out = [
    '/*',
    ' * Dark theme (html.dark): remaps the palette so every page follows without dark: classes.',
    ' * GENERATED by frontend/scripts/build-dark-theme.py (the rules are explained there): do not edit by hand.',
    ' */',
    '',
    'html.dark {',
    '  color-scheme: dark;',
    f'  --color-canvas: {CANVAS};',
    f'  --surface: {SURFACE};',
]
for s, v in SLATE_DARK.items():
    out.append(f'  --color-slate-{s}: {v};')
for h in HUES:
    base = colors[f'{h}-500']
    for s, p in TINT.items():
        out.append(f'  --color-{h}-{s}: color-mix(in oklab, {base} {p}%, {SURFACE});')
out += ['}', '', '/* Dark text shades become light; light text shades keep their colour (they sit on coloured fills). */']
for s, v in SLATE_TEXT.items():
    out.append(text_rule(f'text-slate-{s}', v))
    out.append(f':where(html.dark) .{esc(f"fill-slate-{s}")} {{ fill: {v}; }}')
for h in HUES:
    for s, up in TEXT_UP.items():
        out.append(text_rule(f'text-{h}-{s}', colors[f'{h}-{up}']))
    for s in (50, 100, 200, 300):
        out.append(text_rule(f'text-{h}-{s}', colors[f'{h}-{s}']))

out += ['', '/* White surfaces (cards, inputs, menus) take the dark surface; white text and borders stay white. */']
white = ['bg-white', 'hover:bg-white', 'focus:bg-white']
out.append(', '.join(f':where(html.dark) .{esc(c)}' + (':hover' if c.startswith('hover:') else ':focus' if c.startswith('focus:') else '') for c in white) + ' { background-color: var(--surface); }')
# Low opacities are "glass" on photos and coloured fills: those stay white.
for n in (50, 60, 70, 80, 85, 90, 95):
    out.append(f':where(html.dark) .{esc(f"bg-white/{n}")} {{ background-color: color-mix(in oklab, var(--surface) {n}%, transparent); }}')
out += [
    ':where(html.dark) .ring-white { --tw-ring-color: var(--surface); }',
    ':where(html.dark) .to-white { --tw-gradient-to: var(--surface); }',
    ':where(html.dark) .from-white { --tw-gradient-from: var(--surface); }',
    '',
]
with open(os.path.join(ROOT, 'src', 'styles', 'dark.css'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(out))
print('wrote src/styles/dark.css')
